### ISSUE TITLE
Specify permissive license.

### ISSUE THREAD

**Issue by dmitshur** [go-gl/example#62]
We should make it clear that anyone can copy/paste code from examples and not feel bad or uncertain about being able to do so. That's one of the reasons the examples exist.

What's a good fit? MIT is permissive, but it makes people have to preserve license and copyright notice, which is too much effort. Public domain perhaps? Or is there a better solution?

**Comment by pwaller** [comment]
Agree with sentiment. No knowledge of licenses though so can't weigh in there.

**Comment by dt-rush** [comment]
I'm pretty sure if there's no LICENSE, we have an even more permissive license than MIT ;)

**Comment by dawidd6** [comment]
There is [Unlicense](https://unlicense.org)

**Comment by slimsag** [comment]
> I'm pretty sure if there's no LICENSE, we have an even more permissive license than MIT ;)

This is not correct from a legal standpoint. If there is no license, the code is as good as proprietary. Using code without a license is a lot like using someone's property/car/home without having permission to do so.

> There is Unlicense

Unlicense is not very permissive as it unfortunately is e.g. not legal in Germany and some other regions, see https://softwareengineering.stackexchange.com/a/147120

> Public domain perhaps?

Same problem as Unlicense, in some countries you cannot legally relinquish your rights so it is effectively the same as if the code didn't have a license in those countries. More explanation here: https://opensource.org/faq#public-domain

There is also CC0, but it debatable if that actually solves the problems due to some patent wording: https://opensource.org/faq#cc-zero

Really, there isn't a good license for doing this that is well-known, and it being well-known is a huge part of the problem: Everyone knows how to use MIT code appropriately and legally, but do you / your company know how to use CC0 or Unlicense code? Probably not.

At the end of the day, all the contributors to this repository are doing so in good faith that anyone can use the code -- so nobody is going to go around suing people for using code they contributed to this repo anyway. But having an MIT license at least makes that clear.

**Comment by pwaller** [comment]
Let's do this. Absent a better suggestion, I agree with @slimsag's reasoning.

This snippet shows lines of surviving code in the repository by author:

```
git ls-files -z | xargs -0n1 git blame -w | perl -n -e '/^.*\((.*?)\s*[\d]{4}/; print $1,"\n"' | sort -f | uniq -c | sort -n
```

```
      7 Matjaz Muhic
   1679 Dmitri Shuralyov
   1977 Eric Woroshow
```

Looking at the diff, I conclude we need @dmitshur and @errcw to agree to license the code as MIT.

* I assume @dmitshur is OK with this from the thumbs up above.
* @errcw: Please can you reply to confirm if you're OK with the MIT license or not?
* @depy also contributed some trivial lint warning fixes.

I think we can add an MIT license to the repo as soon as we have input from the above people.
