### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by pwolf23** [go-gl/example#63]
The examples contain references to external resources (e.g. "github.com/go-gl/examples/data/bitmap_font.png"), which do not exist.

Edit: Sorry, I intended to put the issue in the gltext repo. But I guess this repo is part of the issue. However the gltext examples are broken!

**Comment by shurcooL** [comment]
> However the gltext examples are broken!

Where do you see gltext examples? Are you looking at a very old commit of this repository?

In any case, gltext is in poor shape and not supported. No one seems to have bandwidth for it. See https://github.com/go-gl/gltext/issues/21. I'll close it because there's no issue in this repository (this repository is actively supported and in good shape).
